# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@fortawesome/fontawesome-free-5.15.2" = {
      name = "_at_fortawesome_slash_fontawesome-free";
      packageName = "@fortawesome/fontawesome-free";
      version = "5.15.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fortawesome/fontawesome-free/-/fontawesome-free-5.15.2.tgz";
        sha512 = "7l/AX41m609L/EXI9EKH3Vs3v0iA8tKlIOGtw+kgcoanI7p+e4I4GYLqW3UXWiTnjSFymKSmTTPKYrivzbxxqA==";
      };
    };
    "codemirror-5.59.4" = {
      name = "codemirror";
      packageName = "codemirror";
      version = "5.59.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/codemirror/-/codemirror-5.59.4.tgz";
        sha512 = "achw5JBgx8QPcACDDn+EUUXmCYzx/zxEtOGXyjvLEvYY8GleUrnfm5D+Zb+UjShHggXKDT9AXrbkBZX6a0YSQg==";
      };
    };
    "iframe-resizer-4.3.2" = {
      name = "iframe-resizer";
      packageName = "iframe-resizer";
      version = "4.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/iframe-resizer/-/iframe-resizer-4.3.2.tgz";
        sha512 = "gOWo2hmdPjMQsQ+zTKbses08mDfDEMh4NneGQNP4qwePYujY1lguqP6gnbeJkf154gojWlBhIltlgnMfYjGHWA==";
      };
    };
    "jquery-3.5.1" = {
      name = "jquery";
      packageName = "jquery";
      version = "3.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery/-/jquery-3.5.1.tgz";
        sha512 = "XwIBPqcMn57FxfT+Go5pzySnm4KWkT1Tv7gjrpT1srtf8Weynl6R273VJ5GjkRb51IzMp5nbaPjJXMWeju2MKg==";
      };
    };
    "jquery-ui-dist-1.12.1" = {
      name = "jquery-ui-dist";
      packageName = "jquery-ui-dist";
      version = "1.12.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery-ui-dist/-/jquery-ui-dist-1.12.1.tgz";
        sha1 = "5c0815d3cc6f90ff5faaf5b268a6e23b4ca904fa";
      };
    };
    "jquery-ui-themes-1.12.0" = {
      name = "jquery-ui-themes";
      packageName = "jquery-ui-themes";
      version = "1.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery-ui-themes/-/jquery-ui-themes-1.12.0.tgz";
        sha1 = "a57ba0ad96800d84522fe76893ffcbde67081d51";
      };
    };
    "mathjax-3.1.2" = {
      name = "mathjax";
      packageName = "mathjax";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/mathjax/-/mathjax-3.1.2.tgz";
        sha512 = "BojKspBv4nNWzO1wC6VEI+g9gHDOhkaGHGgLxXkasdU4pwjdO5AXD5M/wcLPkXYPjZ/N+6sU8rjQTlyvN2cWiQ==";
      };
    };
    "nestedSortable-1.3.4" = {
      name = "nestedSortable";
      packageName = "nestedSortable";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/nestedSortable/-/nestedSortable-1.3.4.tgz";
        sha1 = "23bcd4294462ba117c1751ef570ded14cbae3354";
      };
    };
  };
  args = {
    name = "webwork.javascript_package_manager";
    packageName = "webwork.javascript_package_manager";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."@fortawesome/fontawesome-free-5.15.2"
      sources."codemirror-5.59.4"
      sources."iframe-resizer-4.3.2"
      sources."jquery-3.5.1"
      sources."jquery-ui-dist-1.12.1"
      sources."jquery-ui-themes-1.12.0"
      sources."mathjax-3.1.2"
      sources."nestedSortable-1.3.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Third party javascript for WeBWorK";
      license = "GPL-2.0+";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
